这里关于数据获取……
股票数据根据信息来源和分析方法的不同，可以分为技术面数据和基本面数据。

技术面数据的常见指标：

- 移动平均线：计算一段时间内的股票平均价格来平滑价格波动，应用于确定趋势、交叉信号和支撑与阻力线（控制上下浮动）。
- 相对强弱指数：衡量股票价格波动强度和速度，是一种短期指标判断超卖或者超买。
- 随机指标：判断股票价格的超买和超卖情况，以及价格反转的可能性。
- 成交量指标：衡量了股票交易的活跃程度。
- MACD 指标：股票技术分析中常用的趋势追踪和买卖信号指标。
  
基本面数据常见指标：

- 每股收益
- 市净率：衡量股票当前市场价格与公司每股净资产之间关系的指标
- 股息收益率：衡量股票派发的股息相对于股票的价格的比率。
- 净利润：衡量一家公司在特定会计期间内实际获得的净收益
- 负债与资产比率：衡量资本结构和债务风险水平

接下来实战获取数据……

In [1]:
import baostock as bs
import pandas as pd
from IPython.display import display

#### 登陆系统 ####
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)

#### 获取沪深A股历史K线数据 ####
# 详细指标参数，参见“历史行情指标参数”章节；“分钟线”参数与“日线”参数不同。“分钟线”不包含指数。
# 分钟线指标：date,time,code,open,high,low,close,volume,amount,adjustflag
# 周月线指标：date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
rs = bs.query_history_k_data_plus("sh.600000",
    "date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST",
    start_date='2023-07-01', end_date='2023-12-31',
    frequency="d", adjustflag="3")
print('query_history_k_data_plus respond error_code:'+rs.error_code)
print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

#### 打印结果集 ####
data_list = []
while (rs.error_code == '0') & rs.next():
    # 获取一条记录，将记录合并在一起
    data_list.append(rs.get_row_data())
result = pd.DataFrame(data_list, columns=rs.fields)

#### 结果集输出到csv文件 ####   
result.to_csv("./history_A_stock_k_data.csv", index=False)
display(result)

#### 登出系统 ####
bs.logout()

login success!
login respond error_code:0
login respond  error_msg:success
query_history_k_data_plus respond error_code:0
query_history_k_data_plus respond  error_msg:success

,date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST
0,2022-07-01,sh.600000,8.0100,8.0400,7.9800,7.9900,8.0100,17846787,142651655.1700,3,0.060800,1,-0.249700,0
1,2022-07-04,sh.600000,7.9900,8.0000,7.9400,7.9600,7.9900,18222009,145047089.1700,3,0.062100,1,-0.375500,0
2,2022-07-05,sh.600000,7.9600,8.0000,7.9400,7.9800,7.9600,21322243,169924262.9100,3,0.072600,1,0.251300,0
3,2022-07-06,sh.600000,7.9700,7.9800,7.8700,7.9000,7.9800,28829658,227963132.4700,3,0.098200,1,-1.002500,0
4,2022-07-07,sh.600000,7.8800,7.9200,7.8600,7.8700,7.9000,18636395,147034169.9300,3,0.063500,1,-0.379700,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,2022-12-26,sh.600000,7.1900,7.2100,7.0800,7.1000,7.1900,20138533,143606823.7100,3,0.068600,1,-1.251700,0
121,2022-12-27,sh.600000,7.1300,7.2900,7.1200,7.2200,7.1000,24065192,173516852.3700,3,0.082000,1,1.690100,0
122,2022-12-28,sh.600000,7.2200,7.3000,7.2000,7.3000,7.2200,20901364,152167733.8100,3,0.071200,1,1.108000,0
123,2022-12-29,sh.600000,7.2700,7.2900,7.1800,7.2400,7.3000,18367088,132652083.0000,3,0.062600,1,-0.821900,0
124,2022-12-30,sh.600000,7.2300,7.3000,7.2200,7.2800,7.2400,20352397,147932730.7100,3,0.069300,1,0.552500,0

logout success!